name: recipe_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  riverpod: ^2.5.4
  json_annotation: ^4.4.0
  uuid: ^3.0.6

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
